# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team_register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(help_text="Member's name", max_length=50, null=True)),
                ('member_email', models.EmailField(help_text="Member's Email ID", max_length=50, null=True)),
                ('member_contact', models.IntegerField(help_text="Member's Contact Number", null=True)),
                ('id_proof', models.ImageField(blank=True, null=True, upload_to=team_register.models.Member.user_directory_path)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Enter your team name', max_length=50)),
                ('total_members', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1', help_text='Total Team Members')),
                ('city', models.CharField(help_text='City/Town', max_length=200)),
                ('state', models.CharField(help_text='State', max_length=200)),
                ('team_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
