# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 20:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_contact',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
