# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0002_auto_20170603_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='total_members',
        ),
        migrations.AddField(
            model_name='teammodel',
            name='total_team_members',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default='1'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
