# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_register', '0005_auto_20170529_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
