# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_register', '0007_remove_team_team_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
