# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-17 05:10
from __future__ import unicode_literals

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='phase_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_images', models.IntegerField(blank=True, help_text='Number of images of existing problems', null=True)),
                ('problem_images_upload', models.ImageField(blank=True, null=True, upload_to=dashboard.models.phase_1.upload_path1)),
                ('FIR_number', models.IntegerField(blank=True, help_text='Number of FIRs to be uploaded', null=True)),
                ('FIR_upload', models.FileField(blank=True, null=True, upload_to=dashboard.models.phase_1.upload_path2)),
                ('news_articles_number', models.IntegerField(blank=True, help_text='Number of News Articles', null=True)),
                ('news_articles_upload', models.FileField(blank=True, null=True, upload_to=dashboard.models.phase_1.upload_path3)),
                ('miscellaneous_upload', models.FileField(blank=True, null=True, upload_to=dashboard.models.phase_1.upload_path4)),
                ('miscellaneous_detail', models.CharField(blank=True, help_text='Description of the miscellaneous file uploaded', max_length=200, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
